### ISSUE TITLE
Updating Civi

### ISSUE THREAD

**Issue by yosefromano** [freeform/civicrm-drupal-pantheon#3]
The 4.7 version Civi that is used requires a security update.
Which patches from the patches directory need to be applied on the new version? Are there patches that are needed that are not in the patches directory?

Thanks

**Comment by herbdool** [comment]
I've applied the 4.7.17 update. Warning that we are not using this branch so we have not tested it at all.

I've disabled the patches for IPN since CiviCRM has a different method for accessing IPN with Paypal that doesn't require calling the extern/ipn.php file directly.
