### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by emilyf** [freeform/civicrm-drupal-pantheon#4]
Hi Herb,

Trying to find a way to contact you. Am hoping I can contract you out to set up these Civi patches on a pantheon instance and document the process in detail. Curious if this solves all the "bad gateways" and other random errors that seem to crop up with Civi on pantheon. 

If you could contact me at emily [at] firstturnmedia [dot] com I'd greatly appreciate chatting with you. Thanks!

**Comment by herbdool** [comment]
Hi Emily,

I've sent you an email.
